name: Build and Deploy Lance Certo

on:
  push:
    branches: [master]  # ou outra branch que você estiver usando

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Buildar a aplicação
        run: dotnet build --configuration Release --no-restore

      - name: Publicar a aplicação
        run: dotnet publish --configuration Release --output ./publish --runtime win-x86

      - name: Deploy via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
